---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: waheed-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waheed-api
  template:
    metadata:
      labels:
        app: waheed-api
    spec:
      containers:
        - name: waheed-api
          image: us-docker.pkg.dev/cit262-team1-project/waheed-api/api-tests
          ports:
            - conainerPort: 3000
          resources:
            limits:
              cpu: ".5"
              memory: 500Mi
            requests:
              cpu: ".25"
              memory: 250Mi
          livenessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            failureThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 10
          startupProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            failureThreshold: 30
            periodSeconds: 30
            timeoutSeconds: 30
