apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-tests
  labels:
    app: api-tests
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-tests
  template:
    metadata:
      labels:
        app: api-tests
    spec:
      containers:
        - name: api-tests
          image: us-docker.pkg.dev/cit262-team1-project/waheed-api/api-tests
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 64m
              memory: 256Mi